/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "math-controller/pkg/apis/mathematics/v1alpha1"
	scheme "math-controller/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MathsGetter has a method to return a MathInterface.
// A group's client should implement this interface.
type MathsGetter interface {
	Maths(namespace string) MathInterface
}

// MathInterface has methods to work with Math resources.
type MathInterface interface {
	Create(ctx context.Context, math *v1alpha1.Math, opts v1.CreateOptions) (*v1alpha1.Math, error)
	Update(ctx context.Context, math *v1alpha1.Math, opts v1.UpdateOptions) (*v1alpha1.Math, error)
	UpdateStatus(ctx context.Context, math *v1alpha1.Math, opts v1.UpdateOptions) (*v1alpha1.Math, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Math, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MathList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Math, err error)
	MathExpansion
}

// maths implements MathInterface
type maths struct {
	client rest.Interface
	ns     string
}

// newMaths returns a Maths
func newMaths(c *MathematicsV1alpha1Client, namespace string) *maths {
	return &maths{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the math, and returns the corresponding math object, and an error if there is any.
func (c *maths) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Math, err error) {
	result = &v1alpha1.Math{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("maths").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Maths that match those selectors.
func (c *maths) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MathList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MathList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("maths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested maths.
func (c *maths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("maths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a math and creates it.  Returns the server's representation of the math, and an error, if there is any.
func (c *maths) Create(ctx context.Context, math *v1alpha1.Math, opts v1.CreateOptions) (result *v1alpha1.Math, err error) {
	result = &v1alpha1.Math{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("maths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(math).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a math and updates it. Returns the server's representation of the math, and an error, if there is any.
func (c *maths) Update(ctx context.Context, math *v1alpha1.Math, opts v1.UpdateOptions) (result *v1alpha1.Math, err error) {
	result = &v1alpha1.Math{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("maths").
		Name(math.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(math).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *maths) UpdateStatus(ctx context.Context, math *v1alpha1.Math, opts v1.UpdateOptions) (result *v1alpha1.Math, err error) {
	result = &v1alpha1.Math{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("maths").
		Name(math.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(math).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the math and deletes it. Returns an error if one occurs.
func (c *maths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("maths").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *maths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("maths").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched math.
func (c *maths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Math, err error) {
	result = &v1alpha1.Math{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("maths").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
