/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "math-controller/pkg/apis/mathematics/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMaths implements MathInterface
type FakeMaths struct {
	Fake *FakeMathematicsV1alpha1
	ns   string
}

var mathsResource = schema.GroupVersionResource{Group: "mathematics.com", Version: "v1alpha1", Resource: "maths"}

var mathsKind = schema.GroupVersionKind{Group: "mathematics.com", Version: "v1alpha1", Kind: "Math"}

// Get takes name of the math, and returns the corresponding math object, and an error if there is any.
func (c *FakeMaths) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Math, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mathsResource, c.ns, name), &v1alpha1.Math{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Math), err
}

// List takes label and field selectors, and returns the list of Maths that match those selectors.
func (c *FakeMaths) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MathList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mathsResource, mathsKind, c.ns, opts), &v1alpha1.MathList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MathList{ListMeta: obj.(*v1alpha1.MathList).ListMeta}
	for _, item := range obj.(*v1alpha1.MathList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested maths.
func (c *FakeMaths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mathsResource, c.ns, opts))

}

// Create takes the representation of a math and creates it.  Returns the server's representation of the math, and an error, if there is any.
func (c *FakeMaths) Create(ctx context.Context, math *v1alpha1.Math, opts v1.CreateOptions) (result *v1alpha1.Math, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mathsResource, c.ns, math), &v1alpha1.Math{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Math), err
}

// Update takes the representation of a math and updates it. Returns the server's representation of the math, and an error, if there is any.
func (c *FakeMaths) Update(ctx context.Context, math *v1alpha1.Math, opts v1.UpdateOptions) (result *v1alpha1.Math, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mathsResource, c.ns, math), &v1alpha1.Math{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Math), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMaths) UpdateStatus(ctx context.Context, math *v1alpha1.Math, opts v1.UpdateOptions) (*v1alpha1.Math, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mathsResource, "status", c.ns, math), &v1alpha1.Math{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Math), err
}

// Delete takes name of the math and deletes it. Returns an error if one occurs.
func (c *FakeMaths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mathsResource, c.ns, name), &v1alpha1.Math{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMaths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mathsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MathList{})
	return err
}

// Patch applies the patch and returns the patched math.
func (c *FakeMaths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Math, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mathsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Math{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Math), err
}
