apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-deployment
  labels:
    app: math-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: math-app
  template:
    metadata:
      labels:
        app: math-app
    spec:
      containers:
      - name: math-app
        image: nextgen98/priyak:math2
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcredpk

