apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: maths.mathematics.com
spec:
  group: mathematics.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                number1:
                  type: integer
                number2:
                  type: integer
                operation:
                  type: string
            status:
              type: object
              properties:
                lastUpdateTime:
                  type: dateTime
                status:
                  type: string
                message:
                  type: string
      subresources:
        # enables the status subresource
        status: {}
  names:
    kind: Math
    plural: maths
  scope: Namespaced
